const ACTIONS = {
  UPDATE_FAVORITE_PHOTOS: 'UPDATE_FAVORITE_PHOTOS',
  UPDATE_MODAL_INFORMATION: 'UPDATE_MODAL_INFORMATION',
  UPDATE_STATE_PHOTOS: 'UPDATE_STATE_PHOTOS',
  UPDATE_STATE_PHOTOS_BY_TOPICID: 'UPDATE_STATE_PHOTOS_BY_TOPICID',
  UPDATE_STATE_TOPICS: 'UPDATE_STATE_TOPICS',
};

export default ACTIONS;